### ISSUE TITLE
Provider-specific fields not present in entry info

### ISSUE THREAD

**Issue by ml-evs** [ml-evs/odbx.science#11]
Somehow the schema is being generated incorrectly.

**Comment by ml-evs** [comment]
This is now working, in some reduced sense. Currently entry info endpoints can't handle fields containing dictionaries, which are what many of the existing odbx fields consist of. Might have to make a flatter structure, or find a way to document these nested values.

(May be of interest to @CasperWA)

**Comment by CasperWA** [comment]
Great! And very interested, just a bit distracted today 😄 Thanks a bund @ml-evs
