### ISSUE TITLE
Add `nperiodic_dimensions` to structures resources

### ISSUE THREAD

**Issue by CasperWA** [ml-evs/odbx.science#13]
The new `structures` resource property `nperiodic_dimensions` does not seem to be part of your `structures` resources.

It was added in Materials-Consortia/OPTIMADE#278.

**Comment by ml-evs** [comment]
I'm waiting for the next minor release of a certain package before I remake my database :upside_down_face:

**Comment by CasperWA** [comment]
well well well :) Fair enough ;)

**Comment by CasperWA** [comment]
Ping.
