### ISSUE TITLE
info endpoint missing?

### ISSUE THREAD

**Issue by JPBergsma** [ml-evs/odbx.science#45]
During the Optimade tutorial, I tried to access https://odbx.science/info/structures and https://odbx.science/v1/info 
In the json response, I received, there was a 404 error message.

**Comment by ml-evs** [comment]
Hi @JPBergsma, the OPTIMADE implementation for odbx is run off the optimade.odbx.science subdomain, do https://optimade.odbx.science/info should work fine. The root domain serves the HTML GUI which does not need to host an info endpoint.

**Comment by JPBergsma** [comment]
Ok, I just followed the link in the table of the tutorial https://github.com/Materials-Consortia/optimade-tutorial-exercises
It seemed logical to me that this would be the correct subdomain.

**Comment by ml-evs** [comment]
The links in the first column of that table are to the homepages of the database,  not to their OPTIMADE APIs, but the links in the other columns should all be to the correct OPTIMADE subdomain.

**Comment by JPBergsma** [comment]
Yes, you are right. My bad.
