### ISSUE TITLE
Pagination pointing to wrong host

### ISSUE THREAD

**Issue by CasperWA** [ml-evs/odbx.science#9]
Since the upgrade to `optimade.odbx.science` the pagination is broken (still returns links to `odbx.science`).

**Comment by ml-evs** [comment]
Thanks @CasperWA, I guess this means the validator is also broken for pagination...

**Comment by ml-evs** [comment]
In fact, I'll try to fix this in the validator before fixing it here. It's just a case of switching the config value for odbx.

**Comment by ml-evs** [comment]
Fixed upstream
